spring.application.name=Employee

spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:16586/railway
spring.datasource.username=root
spring.datasource.password=AcdLRgbQrUGPgjBsqwJQJCPRuRRVJxNz

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update